mysql:
  db: 	"coai"
  host: "172.0.0.1"
  password: ""
  port: 3306
  user: "coai"
  tls: false

redis:
  host: "172.0.0.1"
  port: 6379
  db: 0
  password: ""


secret: secret
servestatic: true

server:
  port: 8094
  secret: ""

system:
  general:
    backend: ""
  mail:
    host: ""
    port: 465
    username: ""
    password: ""
    from: ""
  search:
    endpoint: https://duckduckgo-api.vercel.app
    query: 5
